import random

MIN_RAND_NUM = 0
MAX_RAND_NUM = 10
GRID_WIDTH = 100
GRID_HEIGHT = 100

DIFFUSION_RATE = 0.01 

GRID_PLOT_COLORS = ['#bedbff', '#51a2ff', '#155dfc', '#1c398e', '#162456']

LOOP_TIME = 50
PAUSE_INTERVAL = 0.1

HORIZONTAL_VEL_ADD_AMOUNT = -1
VERTICAL_VEL_ADD_AMOUNT = 0
TIME_STEP = 0.05
FORCE_STRENGTH = 5

OBSTACLE_X_START = 2
OBSTACLE_X_END = 5
OBSTACLE_Y_START = 3
OBSTACLE_Y_END = 7

CIRCLE_X_POS = 40
CIRCLE_Y_POS = 40
CIRCLE_RADIUS = 5

def getRandomGridNum():
    return random.randint(MIN_RAND_NUM, MAX_RAND_NUM)